name: ldsc_munge
channels:
  - defaults
  - bioconda
dependencies:
  - python=2.7
  - argparse
  - bitarray=0.8
  - nose=1.3
  #- numpy>=1.12
  - scipy>=0.18
  - pip
  # - pybedtools=0.7 # only needed for make_annot.py
  - pip: # following added under pip to avoid conda 'ResolvePackageNotFound' error
    - pandas==0.20.1 
    - numpy==1.13.1
    # ^ pandas==0.20.1 numpy==1.11.3 WORKS.
    # ^ pandas==0.20.1 numpy==1.13.1 WORKS.
    # ^ for some reason pandas does 0.20 does not work with numpy 1.6.4 (and possibly other newer versions of of numpy. munge_ldsc.py will 'hang' forever during "Reading sumstats from <GWAS DATAFILE> into memory 5000000 SNPs at a time"

#### mtag dependencies
# - argparse
# - joblib
# - python=2.7
# - bitarray=0.8
# - numpy>=1.13.1
# - pandas>=0.18.1
# - scipy>=0.18
